name: 'PR Branch Name'
description: 'Sets the PR Branch Name for other steps'
inputs:
  repo-token:
    description: 'GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
